apiVersion: apps/v1
kind: Deployment
metadata:
  name: pod-cliente-api
  labels:
    app: pod-cliente-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pod-cliente-api
  template:
    metadata:
      labels:
        app: pod-cliente-api
    spec:
      containers:
        - name: backend-cliente-api
          image: 975714002932.dkr.ecr.us-east-1.amazonaws.com/pos-fiap-schepis/cliente-service:latest
          ports:
            - containerPort: 8080
          resources:
            requests:
              memory: "512Mi"
              cpu: "500m"
            limits:
              memory: "1024Mi"
              cpu: "1000m"
          env:
            - name: RDS_HOSTNAME
              value: $RDS_HOSTNAME
            - name: SPRING_PROFILES_ACTIVE
              value: "prod"
            - name: RDS_PORT
              value: "5432"
            - name: RDS_USERNAME
              value: postgres
            - name: RDS_PASSWORD
              value: postgres
            - name: PROFILE
              value: prd
